# SPDX-License-Identifier: GPL-2.0-only
# External object smoke only, not shipping Kbuild.
obj-m += gpueb-adoption-candidate.o
gpueb-adoption-candidate-y := mt6878-gpueb-sram-core.o mt6878-gpueb-sram.o \
	mt6878-gpueb-adoption.o mtk-gpueb-mailbox.o mt6878-gpueb-session.o
