# SPDX-License-Identifier: GPL-2.0-only
# External object smoke only. No packaged Kbuild integration.
obj-m += gpueb-mmio-scope-candidate.o
gpueb-mmio-scope-candidate-y := mt6878-gpueb-io-core.o mt6878-gpueb-io.o
