[Service]
Environment=WLR_RENDERER=pixman
Environment=WLR_RENDERER_ALLOW_SOFTWARE=1
Environment=WLR_DRM_NO_MODIFIERS=1
Environment=WLR_NO_HARDWARE_CURSORS=1
ExecStart=
ExecStart=greetd -c /etc/phrog/tetris-greetd-config.toml
