Syntax 6

SectionVerb {
	EnableSequence [
		cset "name='UL9_CH1 ADDA_UL_CH1' 1"
		cset "name='UL9_CH2 ADDA_UL_CH2' 1"
		cset "name='PGA_L_Mux' AIN0"
		cset "name='PGA_R_Mux' AIN2"
		cset "name='ADC_L_Mux' 'Left Preamplifier'"
		cset "name='ADC_R_Mux' 'Right Preamplifier'"
		cset "name='PGA1 Volume' 4"
		cset "name='PGA2 Volume' 4"
	]

	DisableSequence [
		cset "name='UL9_CH1 ADDA_UL_CH1' 0"
		cset "name='UL9_CH2 ADDA_UL_CH2' 0"
		cset "name='PGA_L_Mux' None"
		cset "name='PGA_R_Mux' None"
		cset "name='ADC_L_Mux' Idle"
		cset "name='ADC_R_Mux' Idle"
		cset "name='PGA1 Volume' 0"
		cset "name='PGA2 Volume' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Main Speaker"
	ConflictingDevice [ "Earpiece" ]

	EnableSequence [
		cset "name='PCM Playback Volume' 0"
		cset "name='I2SOUT4_CH1 DL6_CH1' 1"
		cset "name='I2SOUT4_CH2 DL6_CH2' 1"
	]

	DisableSequence [
		cset "name='I2SOUT4_CH1 DL6_CH1' 0"
		cset "name='I2SOUT4_CH2 DL6_CH2' 0"
	]

	Value {
		PlaybackPCM "hw:${CardId},6"
		PlaybackChannels 2
		PlaybackChannel0 0
		PlaybackChannelPos0 FL
		PlaybackChannel1 1
		PlaybackChannelPos1 FR
		PlaybackRate 48000
		PlaybackPriority 300
	}
}

SectionDevice."Earpiece" {
	Comment "Earpiece"
	ConflictingDevice [ "Speaker" ]

	EnableSequence [
		cset "name='ADDA_DL_CH1 DL6_CH1' 1"
		cset "name='ADDA_DL_CH2 DL6_CH2' 1"
		cset "name='RCV Mux' 'Voice Playback'"
	]

	DisableSequence [
		cset "name='RCV Mux' Open"
		cset "name='ADDA_DL_CH1 DL6_CH1' 0"
		cset "name='ADDA_DL_CH2 DL6_CH2' 0"
	]

	Value {
		PlaybackPCM "hw:${CardId},6"
		PlaybackChannels 2
		PlaybackChannel0 0
		PlaybackChannelPos0 FL
		PlaybackChannel1 1
		PlaybackChannelPos1 FR
		PlaybackRate 48000
		PlaybackPriority 200
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphones"

	Value {
		CapturePCM "hw:${CardId},13"
		CaptureChannels 2
		CaptureRate 48000
		CapturePriority 200
	}
}
