# SPDX-License-Identifier: GPL-2.0-only
# External object smoke harness; not included by the shipping kernel.
obj-m += mt6878-gpueb-sram-candidate.o
mt6878-gpueb-sram-candidate-y := mt6878-gpueb-sram-core.o mt6878-gpueb-sram.o
